### ISSUE TITLE
404

### ISSUE THREAD

**Issue by Nilihum** [frankwking/WiseArtificersInsight#2]
For the last few days at least, maybe longer, http://wiseartificersinsight.com/ has been 404'ing. Is there any chance that it could be brought online? It was really useful and almost a necessity for playing any type of crafter.

While I'm here, is there any chance that this will be updated to include Dragonblooded crafting?

**Comment by frankwking** [comment]
Sorry for the delay, the site is back up.  I had been getting security emails from Github about vulnerable dependencies in a project and didn't have any feedback that people were using the site, so I figured the most secure thing to do was take it down.  Since it does appear that at least 3 people are using it and the security vulnerabilities were actually for something else, I've put it back up.  I hope you enjoy it and continue to find it useful.

As for Dragonbloods, that question is still undecided.  If you'd like to talk about it please raise a separate Issue.

Please respond here that you can see the site, then I'll close the Issue.

**Comment by frankwking** [comment]
Sorry for the delay, the site is back up. I had been getting security emails from Github about vulnerable dependencies in a project and didn't have any feedback that people were using the site, so I figured the most secure thing to do was take it down. Since it does appear that at least 3 people are using it and the security vulnerabilities were actually for something else, I've put it back up. I hope you enjoy it and continue to find it useful.

As for Dragonbloods, that question is still undecided. If you'd like to talk about it please raise a separate Issue.

Please respond here that you can see the site, then I'll close the Issue.

**Comment by Nilihum** [comment]
I am able to see the site. You may close this issue.

**Comment by frankwking** [comment]
Thank you.
